export type SupplierProfile = {
  name: string;
  location: string;
  state: string;
  gstin: string;
  estYear: number;
  rating: number;
  reviewCount: number;
  totalProducts: number;
  description: string;
};

export const supplierProfiles: Record<string, SupplierProfile> = {
  "Bharat Tin Works": {
    name: "Bharat Tin Works",
    location: "Bhiwandi, Maharashtra",
    state: "Maharashtra",
    gstin: "27AABCB1234C1Z5",
    estYear: 1989,
    rating: 4.7,
    reviewCount: 214,
    totalProducts: 38,
    description: "Leading manufacturer of food-grade tin containers and industrial metal packaging for FMCG and pharma sectors.",
  },
  "Metpack Industries": {
    name: "Metpack Industries",
    location: "Ludhiana, Punjab",
    state: "Punjab",
    gstin: "03AADCM4567D1Z2",
    estYear: 1997,
    rating: 4.5,
    reviewCount: 162,
    totalProducts: 29,
    description: "Specialised in embossed and printed tin packaging for gift, confectionery, and retail applications.",
  },
  "Sunrise Metal Co.": {
    name: "Sunrise Metal Co.",
    location: "Rajkot, Gujarat",
    state: "Gujarat",
    gstin: "24AADCS8901E1Z8",
    estYear: 2003,
    rating: 4.6,
    reviewCount: 98,
    totalProducts: 22,
    description: "Airtight and food-grade tin containers, supplying to tea, spice, and processed food manufacturers across India.",
  },
  "National Packaging": {
    name: "National Packaging",
    location: "Noida, Uttar Pradesh",
    state: "Uttar Pradesh",
    gstin: "09AAACN2345F1Z4",
    estYear: 1994,
    rating: 4.4,
    reviewCount: 187,
    totalProducts: 45,
    description: "High-volume packaging components including caps, closures, and tin accessories for industrial and retail supply chains.",
  },
  "Skyline Electronics": {
    name: "Skyline Electronics",
    location: "Noida, Uttar Pradesh",
    state: "Uttar Pradesh",
    gstin: "09AABCS3456G1Z3",
    estYear: 2008,
    rating: 4.6,
    reviewCount: 311,
    totalProducts: 54,
    description: "Authorised distributor of LED and OLED displays for retail chains, hotels, and commercial installations.",
  },
  "VisionTech India": {
    name: "VisionTech India",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    gstin: "36AABCV5678H1Z1",
    estYear: 2011,
    rating: 4.7,
    reviewCount: 229,
    totalProducts: 41,
    description: "Smart TV and commercial display specialist with pan-India distribution and 1-year on-site warranty support.",
  },
  "DigiView Pvt Ltd": {
    name: "DigiView Pvt Ltd",
    location: "Bengaluru, Karnataka",
    state: "Karnataka",
    gstin: "29AABCD6789I1Z9",
    estYear: 2015,
    rating: 4.5,
    reviewCount: 143,
    totalProducts: 18,
    description: "Computer monitors and digital signage solutions for corporates, educational institutions, and government clients.",
  },
  "CoolBreeze Industries": {
    name: "CoolBreeze Industries",
    location: "Ahmedabad, Gujarat",
    state: "Gujarat",
    gstin: "24AABCC7890J1Z6",
    estYear: 2001,
    rating: 4.5,
    reviewCount: 176,
    totalProducts: 31,
    description: "Manufacturer of desert and tower air coolers for residential, commercial, and light industrial use.",
  },
  "AirFlo Systems": {
    name: "AirFlo Systems",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    gstin: "27AABCA8901K1Z4",
    estYear: 2006,
    rating: 4.8,
    reviewCount: 134,
    totalProducts: 26,
    description: "Industrial evaporative cooling and HVAC ducting systems for warehouses, factories, and large commercial spaces.",
  },
  "ClimateMaster Co.": {
    name: "ClimateMaster Co.",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    gstin: "33AABCC9012L1Z2",
    estYear: 2009,
    rating: 4.6,
    reviewCount: 89,
    totalProducts: 14,
    description: "Portable and split AC units designed for commercial deployment with bulk pricing and installation support.",
  },
  "Woodcraft Furnishings": {
    name: "Woodcraft Furnishings",
    location: "Jodhpur, Rajasthan",
    state: "Rajasthan",
    gstin: "08AABCW1234M1Z7",
    estYear: 1985,
    rating: 4.7,
    reviewCount: 258,
    totalProducts: 63,
    description: "Premium commercial and office furniture manufacturer supplying to corporates, hospitality, and institutions.",
  },
  "ModSpace India": {
    name: "ModSpace India",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    gstin: "27AABCM2345N1Z5",
    estYear: 2013,
    rating: 4.4,
    reviewCount: 192,
    totalProducts: 47,
    description: "Modular and affordable office furniture for startups, schools, and mid-size enterprises across India.",
  },
  "ErgoFit Pvt Ltd": {
    name: "ErgoFit Pvt Ltd",
    location: "Bengaluru, Karnataka",
    state: "Karnataka",
    gstin: "29AABCE3456O1Z3",
    estYear: 2017,
    rating: 4.6,
    reviewCount: 107,
    totalProducts: 21,
    description: "Ergonomic and height-adjustable workstations for IT parks, co-working spaces, and corporate campuses.",
  },
  "Bharat Machine Tools": {
    name: "Bharat Machine Tools",
    location: "Coimbatore, Tamil Nadu",
    state: "Tamil Nadu",
    gstin: "33AABCB4567P1Z1",
    estYear: 1976,
    rating: 4.8,
    reviewCount: 341,
    totalProducts: 72,
    description: "Heavy industrial machinery manufacturer with 48 years of precision engineering for automotive, aerospace, and fabrication.",
  },
  "PowerPress Corp": {
    name: "PowerPress Corp",
    location: "Faridabad, Haryana",
    state: "Haryana",
    gstin: "06AABCP5678Q1Z9",
    estYear: 1998,
    rating: 4.6,
    reviewCount: 198,
    totalProducts: 38,
    description: "Hydraulic presses, conveyor systems, and industrial bench equipment for manufacturing plants.",
  },
  "MetalCraft Systems": {
    name: "MetalCraft Systems",
    location: "Surat, Gujarat",
    state: "Gujarat",
    gstin: "24AABCM6789R1Z7",
    estYear: 2004,
    rating: 4.5,
    reviewCount: 154,
    totalProducts: 29,
    description: "Metal cutting and welding equipment, designed for medium-to-large scale fabrication workshops.",
  },
  "Polyplast India": {
    name: "Polyplast India",
    location: "Vadodara, Gujarat",
    state: "Gujarat",
    gstin: "24AABCP7890S1Z5",
    estYear: 1992,
    rating: 4.7,
    reviewCount: 223,
    totalProducts: 34,
    description: "Bulk polymer and plastic granule supplier with ISO-certified manufacturing and pan-India logistics.",
  },
  "ChemSource Pvt Ltd": {
    name: "ChemSource Pvt Ltd",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    gstin: "27AABCC8901T1Z3",
    estYear: 2000,
    rating: 4.5,
    reviewCount: 179,
    totalProducts: 41,
    description: "Industrial polymer and specialty chemical distributor serving packaging, automotive, and construction sectors.",
  },
  "IndoPolymers": {
    name: "IndoPolymers",
    location: "Surat, Gujarat",
    state: "Gujarat",
    gstin: "24AABCI9012U1Z1",
    estYear: 2007,
    rating: 4.6,
    reviewCount: 148,
    totalProducts: 27,
    description: "Film-grade and engineering polymer granules for flexible packaging, pipes, and injection moulding applications.",
  },
};

export function getSupplier(name: string): SupplierProfile | null {
  return supplierProfiles[name] ?? null;
}
