import type { Order, ActiveVendor, PendingVendor } from "./types";

export const ORDERS: Order[] = [
  {
    id: "ORD-2024-001",
    buyer: "Ramesh Industries Pvt. Ltd.",
    buyerEmail: "procurement@rameshindustries.in",
    buyerPhone: "+91 98201 34567",
    buyerCity: "Mumbai, Maharashtra",
    product: "Wheat (Grade A)",
    category: "Grains & Cereals",
    quantity: "50 MT",
    unitPrice: "₹37,000/MT",
    amount: "₹18,50,000",
    vendor: "Punjab Agro Traders",
    vendorId: "VND-001",
    status: "Ready for Dispatch",
    date: "2024-11-28",
    shippingProvider: "Gati Logistics",
    deliveryAddress: "Warehouse 4, APMC Vashi, Navi Mumbai",
    paymentRef: "CCR-20241128-8821",
    settlementStatus: "Pending",
    settlementAmount: "₹17,39,250",
    shipmentPhotosUploaded: true,
    buyerVerified: true,
  },
  {
    id: "ORD-2024-002",
    buyer: "Metro Retail Chain Ltd.",
    buyerEmail: "orders@metroretail.co.in",
    buyerPhone: "+91 97654 12890",
    buyerCity: "Delhi, NCR",
    product: "Basmati Rice (1121)",
    category: "Grains & Cereals",
    quantity: "30 MT",
    unitPrice: "₹80,000/MT",
    amount: "₹24,00,000",
    vendor: "Haryana Rice Mills",
    vendorId: "VND-002",
    status: "Accepted",
    date: "2024-11-29",
    shippingProvider: "Blue Dart Freight",
    deliveryAddress: "Plot 12, Naraina Industrial Area Phase 2, Delhi",
    paymentRef: "CCR-20241129-9034",
    settlementStatus: "On Hold",
    settlementAmount: "₹22,56,000",
    shipmentPhotosUploaded: false,
    buyerVerified: false,
  },
  {
    id: "ORD-2024-003",
    buyer: "Sunrise Exports LLP",
    buyerEmail: "ops@sunriseexports.in",
    buyerPhone: "+91 94481 78900",
    buyerCity: "Surat, Gujarat",
    product: "Refined Sunflower Oil",
    category: "Edible Oils",
    quantity: "200 Drums (18,000 L)",
    unitPrice: "₹120/L",
    amount: "₹21,60,000",
    vendor: "Gujarat Oil Refineries",
    vendorId: "VND-003",
    status: "Paid",
    date: "2024-11-30",
    shippingProvider: "VRL Logistics",
    deliveryAddress: "Surat Port Trust Yard, Magdalla Port, Surat",
    paymentRef: "CCR-20241130-9245",
    settlementStatus: "N/A",
    settlementAmount: "₹20,30,400",
    shipmentPhotosUploaded: false,
    buyerVerified: false,
  },
  {
    id: "ORD-2024-004",
    buyer: "National Food Corp",
    buyerEmail: "supply@nationalfoodcorp.in",
    buyerPhone: "+91 99900 12345",
    buyerCity: "Hyderabad, Telangana",
    product: "Yellow Maize",
    category: "Grains & Cereals",
    quantity: "100 MT",
    unitPrice: "₹22,500/MT",
    amount: "₹22,50,000",
    vendor: "Madhya Pradesh Agri Co.",
    vendorId: "VND-004",
    status: "Completed",
    date: "2024-11-15",
    shippingProvider: "TCI Freight",
    deliveryAddress: "NFCL Godown, Nacharam, Hyderabad",
    paymentRef: "CCR-20241115-7789",
    settlementStatus: "Released",
    settlementAmount: "₹21,15,000",
    settlementDate: "2024-11-18",
    shipmentPhotosUploaded: true,
    buyerVerified: true,
  },
  {
    id: "ORD-2024-005",
    buyer: "Spice World Traders",
    buyerEmail: "bulk@spiceworldtraders.in",
    buyerPhone: "+91 98765 43210",
    buyerCity: "Kochi, Kerala",
    product: "Turmeric Powder (Erode)",
    category: "Spices",
    quantity: "5 MT",
    unitPrice: "₹1,25,000/MT",
    amount: "₹6,25,000",
    vendor: "Rajasthan Spice Exports",
    vendorId: "VND-005",
    status: "Ready for Dispatch",
    date: "2024-11-27",
    shippingProvider: "SafeXpress",
    deliveryAddress: "Jew Town Spice Market, Mattancherry, Kochi",
    paymentRef: "CCR-20241127-8654",
    settlementStatus: "Pending",
    settlementAmount: "₹5,87,500",
    shipmentPhotosUploaded: true,
    buyerVerified: true,
  },
  {
    id: "ORD-2024-006",
    buyer: "AgroTech Solutions Pvt. Ltd.",
    buyerEmail: "purchase@agrotech.in",
    buyerPhone: "+91 97654 33210",
    buyerCity: "Pune, Maharashtra",
    product: "DAP Fertilizer (Bag)",
    category: "Fertilizers",
    quantity: "80 MT (1,600 bags)",
    unitPrice: "₹1,350/bag",
    amount: "₹21,60,000",
    vendor: "Tata Chemicals Distribution",
    vendorId: "VND-006",
    status: "Accepted",
    date: "2024-11-30",
    shippingProvider: "Mahindra Logistics",
    deliveryAddress: "AgroTech Farm Hub, Shirur, Pune",
    paymentRef: "CCR-20241130-9312",
    settlementStatus: "On Hold",
    settlementAmount: "₹20,30,400",
    shipmentPhotosUploaded: false,
    buyerVerified: false,
  },
  {
    id: "ORD-2024-007",
    buyer: "Bharat Cotton Mills Ltd.",
    buyerEmail: "raw@bharatcotton.in",
    buyerPhone: "+91 94490 67823",
    buyerCity: "Ahmedabad, Gujarat",
    product: "Raw Cotton (Shankar-6)",
    category: "Textile Raw Materials",
    quantity: "25 MT",
    unitPrice: "₹64,000/MT",
    amount: "₹16,00,000",
    vendor: "Gujarat Cotton Traders",
    vendorId: "VND-007",
    status: "Completed",
    date: "2024-11-10",
    shippingProvider: "GATI Express",
    deliveryAddress: "Bharat Cotton Factory, Naroda GIDC, Ahmedabad",
    paymentRef: "CCR-20241110-7412",
    settlementStatus: "Released",
    settlementAmount: "₹15,04,000",
    settlementDate: "2024-11-13",
    shipmentPhotosUploaded: true,
    buyerVerified: true,
  },
  {
    id: "ORD-2024-008",
    buyer: "South India Proteins Pvt. Ltd.",
    buyerEmail: "procurement@siprotein.in",
    buyerPhone: "+91 96654 23001",
    buyerCity: "Chennai, Tamil Nadu",
    product: "Soya Bean Meal (DOC)",
    category: "Animal Feed",
    quantity: "40 MT",
    unitPrice: "₹40,000/MT",
    amount: "₹16,00,000",
    vendor: "Madhya Pradesh Agri Co.",
    vendorId: "VND-004",
    status: "Paid",
    date: "2024-12-01",
    shippingProvider: "DTDC Cargo",
    deliveryAddress: "SI Proteins Processing Unit, Ambattur, Chennai",
    paymentRef: "CCR-20241201-9501",
    settlementStatus: "N/A",
    settlementAmount: "₹15,04,000",
    shipmentPhotosUploaded: false,
    buyerVerified: false,
  },
  {
    id: "ORD-2024-009",
    buyer: "Himalayan Herbs Pvt. Ltd.",
    buyerEmail: "orders@himherbs.in",
    buyerPhone: "+91 98110 45678",
    buyerCity: "Dehradun, Uttarakhand",
    product: "Dry Red Chilli (Byadagi)",
    category: "Spices",
    quantity: "8 MT",
    unitPrice: "₹95,000/MT",
    amount: "₹7,60,000",
    vendor: "Rajasthan Spice Exports",
    vendorId: "VND-005",
    status: "Completed",
    date: "2024-11-05",
    shippingProvider: "Delhivery Freight",
    deliveryAddress: "Him Herbs Facility, Prem Nagar, Dehradun",
    paymentRef: "CCR-20241105-6987",
    settlementStatus: "Released",
    settlementAmount: "₹7,14,400",
    settlementDate: "2024-11-08",
    shipmentPhotosUploaded: true,
    buyerVerified: true,
  },
  {
    id: "ORD-2024-010",
    buyer: "Delhi Flour Mills Pvt. Ltd.",
    buyerEmail: "purchase@delhiflour.in",
    buyerPhone: "+91 99100 22334",
    buyerCity: "Delhi, NCR",
    product: "Wheat (Sharbati Grade)",
    category: "Grains & Cereals",
    quantity: "75 MT",
    unitPrice: "₹42,000/MT",
    amount: "₹31,50,000",
    vendor: "Punjab Agro Traders",
    vendorId: "VND-001",
    status: "Cancelled",
    date: "2024-11-20",
    shippingProvider: "N/A",
    deliveryAddress: "Delhi Flour Mills, Najafgarh Road, Delhi",
    paymentRef: "CCR-20241120-8234",
    settlementStatus: "N/A",
    settlementAmount: "₹0",
    shipmentPhotosUploaded: false,
    buyerVerified: false,
  },
];

export const ACTIVE_VENDORS: ActiveVendor[] = [
  {
    id: "VND-001",
    name: "Punjab Agro Traders",
    email: "contact@punjabagrotraders.in",
    phone: "+91 98140 12345",
    gstin: "03AABCP1234M1ZX",
    pan: "AABCP1234M",
    ordersAccepted: 14,
    ordersCompleted: 12,
    totalSettled: "₹1,24,00,000",
    pendingSettlement: "₹18,50,000",
    category: "Grains & Cereals",
    joinedDate: "2024-06-10",
    rating: 4.7,
    city: "Ludhiana",
    state: "Punjab",
    accountHolder: "Punjab Agro Traders",
    bankName: "Punjab National Bank",
    ifsc: "PUNB0012345",
    status: "Active",
    lastActivity: "2024-11-28",
  },
  {
    id: "VND-002",
    name: "Haryana Rice Mills",
    email: "admin@haryanaricemill.in",
    phone: "+91 94161 67890",
    gstin: "06AABHM4567K1ZY",
    pan: "AABHM4567K",
    ordersAccepted: 9,
    ordersCompleted: 7,
    totalSettled: "₹86,00,000",
    pendingSettlement: "₹24,00,000",
    category: "Grains & Cereals",
    joinedDate: "2024-07-22",
    rating: 4.5,
    city: "Karnal",
    state: "Haryana",
    accountHolder: "Haryana Rice Mills Pvt Ltd",
    bankName: "State Bank of India",
    ifsc: "SBIN0006789",
    status: "Active",
    lastActivity: "2024-11-29",
  },
  {
    id: "VND-003",
    name: "Gujarat Oil Refineries",
    email: "sales@gujaratoil.in",
    phone: "+91 98250 34567",
    gstin: "24AACPG8901N1ZW",
    pan: "AACPG8901N",
    ordersAccepted: 21,
    ordersCompleted: 19,
    totalSettled: "₹2,08,00,000",
    pendingSettlement: "₹21,60,000",
    category: "Edible Oils",
    joinedDate: "2024-04-15",
    rating: 4.8,
    city: "Rajkot",
    state: "Gujarat",
    accountHolder: "Gujarat Oil Refineries Ltd",
    bankName: "HDFC Bank",
    ifsc: "HDFC0009012",
    status: "Active",
    lastActivity: "2024-11-30",
  },
  {
    id: "VND-004",
    name: "Madhya Pradesh Agri Co.",
    email: "ops@mpagrico.in",
    phone: "+91 94255 78901",
    gstin: "23AAECM2345Q1ZV",
    pan: "AAECM2345Q",
    ordersAccepted: 8,
    ordersCompleted: 6,
    totalSettled: "₹72,50,000",
    pendingSettlement: "₹16,00,000",
    category: "Grains & Cereals",
    joinedDate: "2024-09-01",
    rating: 4.3,
    city: "Indore",
    state: "Madhya Pradesh",
    accountHolder: "MP Agri Co. Partnership",
    bankName: "Bank of Baroda",
    ifsc: "BARB0INDORE",
    status: "Active",
    lastActivity: "2024-12-01",
  },
  {
    id: "VND-005",
    name: "Rajasthan Spice Exports",
    email: "export@rajspices.in",
    phone: "+91 94141 23456",
    gstin: "08AACRJ6789R1ZU",
    pan: "AACRJ6789R",
    ordersAccepted: 18,
    ordersCompleted: 16,
    totalSettled: "₹95,00,000",
    pendingSettlement: "₹13,85,000",
    category: "Spices",
    joinedDate: "2024-05-30",
    rating: 4.6,
    city: "Jodhpur",
    state: "Rajasthan",
    accountHolder: "Rajasthan Spice Exports LLP",
    bankName: "Axis Bank",
    ifsc: "UTIB0003456",
    status: "Active",
    lastActivity: "2024-11-27",
  },
  {
    id: "VND-006",
    name: "Tata Chemicals Distribution",
    email: "trade@tatachem.in",
    phone: "+91 22 6665 8888",
    gstin: "27AAACT2727Q1ZF",
    pan: "AAACT2727Q",
    ordersAccepted: 5,
    ordersCompleted: 4,
    totalSettled: "₹1,12,00,000",
    pendingSettlement: "₹21,60,000",
    category: "Fertilizers",
    joinedDate: "2024-10-05",
    rating: 4.9,
    city: "Mumbai",
    state: "Maharashtra",
    accountHolder: "Tata Chemicals Ltd",
    bankName: "ICICI Bank",
    ifsc: "ICIC0001234",
    status: "Active",
    lastActivity: "2024-11-30",
  },
  {
    id: "VND-007",
    name: "Gujarat Cotton Traders",
    email: "cotton@gctrades.in",
    phone: "+91 98790 56789",
    gstin: "24AADCG5678S1ZT",
    pan: "AADCG5678S",
    ordersAccepted: 4,
    ordersCompleted: 4,
    totalSettled: "₹56,00,000",
    pendingSettlement: "₹0",
    category: "Textile Raw Materials",
    joinedDate: "2024-08-18",
    rating: 4.4,
    city: "Ahmedabad",
    state: "Gujarat",
    accountHolder: "Gujarat Cotton Traders Pvt Ltd",
    bankName: "Union Bank of India",
    ifsc: "UBIN0567890",
    status: "Active",
    lastActivity: "2024-11-12",
  },
];

export const PENDING_VENDORS: PendingVendor[] = [
  {
    id: "PV-001",
    businessName: "Karnataka Pulses Pvt. Ltd.",
    contactName: "Suresh Nagarajan",
    email: "suresh@karpulses.in",
    phone: "+91 94481 23456",
    entityType: "Company",
    category: "Pulses & Lentils",
    city: "Bengaluru",
    state: "Karnataka",
    appliedDate: "2024-11-25",
    status: "Pending",
    agreementFileName: "Karnataka_Pulses_VendorAgreement_v1.pdf",
    agreementSize: "2.4 MB",
    agreementUploadedAt: "2024-11-25 14:32 IST",
    checklist: {
      businessVerification: true,
      gstVerified: true,
      panVerified: true,
      uboVerified: false,
      bankAccountVerified: false,
      agreementSigned: true,
      productReviewApproved: false,
      riskRatingAssigned: false,
      complianceApproval: false,
    },
    documents: {
      gstCertificate: "GST_KAR_33AAKCK1234M1Z5.pdf",
      panCard: "PAN_AAKCK1234M.pdf",
      cancelledCheque: "",
      incorporationCertificate: "COI_KarnatakaPulses_MCA.pdf",
      addressProof: "UtilityBill_Nov2024_KPL.pdf",
      uboAadhaar: "",
      boardResolution: "BoardResolution_KPL_Nov24.pdf",
    },
    ubo: {
      name: "Suresh Nagarajan",
      dob: "12 Mar 1979",
      nationality: "Indian",
      address: "14/2, Indiranagar 100ft Road, Bengaluru - 560038",
      ownershipPct: "68%",
      panVerified: true,
      sanctionsCleared: true,
      pepCleared: true,
    },
    bankDetails: {
      accountHolder: "Karnataka Pulses Pvt. Ltd.",
      bankName: "HDFC Bank",
      ifsc: "HDFC0001234",
      accountNo: "XXXX XXXX 5678",
      pennyDropStatus: "Pending",
      beneficiaryMatch: false,
    },
    riskRating: "Unassigned",
    notes: "UBO Aadhaar pending upload. Cancelled cheque not submitted. Penny drop initiated but awaiting bank response.",
    products: ["Toor Dal", "Chana Dal", "Masoor Dal", "Moong Dal", "Urad Dal"],
  },
  {
    id: "PV-002",
    businessName: "Coastal Seafood Exports LLP",
    contactName: "Priya Menon",
    email: "priya@coastalseafood.in",
    phone: "+91 98765 43210",
    entityType: "LLP",
    category: "Seafood & Marine Products",
    city: "Kochi",
    state: "Kerala",
    appliedDate: "2024-11-20",
    status: "Pending",
    agreementFileName: "CoastalSeafood_VendorAgreement_Signed.pdf",
    agreementSize: "1.8 MB",
    agreementUploadedAt: "2024-11-20 09:15 IST",
    checklist: {
      businessVerification: true,
      gstVerified: true,
      panVerified: true,
      uboVerified: true,
      bankAccountVerified: true,
      agreementSigned: true,
      productReviewApproved: true,
      riskRatingAssigned: true,
      complianceApproval: false,
    },
    documents: {
      gstCertificate: "GST_COASTAL_32AACFC4567P1Z3.pdf",
      panCard: "PAN_AACFC4567P.pdf",
      cancelledCheque: "CancelledCheque_CSE_Axis.pdf",
      incorporationCertificate: "LLP_Certificate_CoastalSeafood.pdf",
      addressProof: "Lease_Kochi_Warehouse_2024.pdf",
      uboAadhaar: "Aadhaar_PriyaMenon_masked.pdf",
      boardResolution: "LLP_Authorization_PriyaMenon.pdf",
    },
    ubo: {
      name: "Priya Menon",
      dob: "5 Jul 1985",
      nationality: "Indian",
      address: "Flat 4B, Marine Drive Apartments, Kochi - 682031",
      ownershipPct: "55%",
      panVerified: true,
      sanctionsCleared: true,
      pepCleared: true,
    },
    bankDetails: {
      accountHolder: "Coastal Seafood Exports LLP",
      bankName: "Axis Bank",
      ifsc: "UTIB0000098",
      accountNo: "XXXX XXXX 9012",
      pennyDropStatus: "Verified",
      beneficiaryMatch: true,
    },
    riskRating: "Low",
    notes: "All checks passed. Awaiting final compliance sign-off from risk team. Expected clearance by Dec 5, 2024.",
    reviewedBy: "Ankit Sharma (Compliance)",
    products: ["Frozen Shrimp (L1)", "Dried Fish", "Cuttlefish", "Prawn (Tiger)"],
  },
  {
    id: "PV-003",
    businessName: "Vijay Cotton Ginners",
    contactName: "Vijay Patil",
    email: "vijay@vijaycotton.in",
    phone: "+91 97654 12345",
    entityType: "Partnership",
    category: "Textile Raw Materials",
    city: "Nagpur",
    state: "Maharashtra",
    appliedDate: "2024-11-28",
    status: "Pending",
    agreementFileName: "VijayCoton_VendorAgreement_Draft.pdf",
    agreementSize: "3.1 MB",
    agreementUploadedAt: "2024-11-28 17:44 IST",
    checklist: {
      businessVerification: false,
      gstVerified: false,
      panVerified: false,
      uboVerified: false,
      bankAccountVerified: false,
      agreementSigned: false,
      productReviewApproved: false,
      riskRatingAssigned: false,
      complianceApproval: false,
    },
    documents: {
      gstCertificate: "GST_VIJAY_27AAHFV3456Q1Z7.pdf",
      panCard: "PAN_AAHFV3456Q.pdf",
      cancelledCheque: "",
      incorporationCertificate: "PartnershipDeed_VijayCoton.pdf",
      addressProof: "UtilityBill_Nagpur_Oct2024.pdf",
      uboAadhaar: "",
      boardResolution: "",
    },
    ubo: {
      name: "Vijay Patil",
      dob: "19 Sep 1972",
      nationality: "Indian",
      address: "Survey No. 45, Hingna Road, Nagpur - 440016",
      ownershipPct: "50%",
      panVerified: false,
      sanctionsCleared: false,
      pepCleared: false,
    },
    bankDetails: {
      accountHolder: "",
      bankName: "",
      ifsc: "",
      accountNo: "",
      pennyDropStatus: "Pending",
      beneficiaryMatch: false,
    },
    riskRating: "Unassigned",
    notes: "Application just received. GST portal verification in progress. Several documents missing. Vendor contacted via email on Nov 29.",
    products: ["Raw Cotton (Shankar-6)", "Cotton Seed", "Cotton Bales"],
  },
  {
    id: "PV-004",
    businessName: "Odisha Cashew Processors Ltd.",
    contactName: "Ranjit Mohapatra",
    email: "ranjit@odishacashew.in",
    phone: "+91 94370 89012",
    entityType: "Company",
    category: "Dry Fruits & Nuts",
    city: "Bhubaneswar",
    state: "Odisha",
    appliedDate: "2024-11-18",
    status: "Pending",
    agreementFileName: "Odisha_Cashew_VendorAgreement_v2.pdf",
    agreementSize: "2.1 MB",
    agreementUploadedAt: "2024-11-18 11:20 IST",
    checklist: {
      businessVerification: true,
      gstVerified: true,
      panVerified: true,
      uboVerified: true,
      bankAccountVerified: true,
      agreementSigned: true,
      productReviewApproved: false,
      riskRatingAssigned: false,
      complianceApproval: false,
    },
    documents: {
      gstCertificate: "GST_OCPL_21AABCO9012R1Z2.pdf",
      panCard: "PAN_AABCO9012R.pdf",
      cancelledCheque: "CancelledCheque_OCPL_SBI.pdf",
      incorporationCertificate: "COI_OdishaCashew_MCA.pdf",
      addressProof: "Lease_Bhubaneswar_Processor_2024.pdf",
      uboAadhaar: "Aadhaar_RanjitMohapatra_masked.pdf",
      boardResolution: "BoardResolution_OCPL_Nov24.pdf",
    },
    ubo: {
      name: "Ranjit Mohapatra",
      dob: "3 Feb 1968",
      nationality: "Indian",
      address: "Plot 22, Unit IV, Bhubaneswar - 751001",
      ownershipPct: "72%",
      panVerified: true,
      sanctionsCleared: true,
      pepCleared: true,
    },
    bankDetails: {
      accountHolder: "Odisha Cashew Processors Ltd.",
      bankName: "State Bank of India",
      ifsc: "SBIN0005678",
      accountNo: "XXXX XXXX 3456",
      pennyDropStatus: "Verified",
      beneficiaryMatch: true,
    },
    riskRating: "Medium",
    notes: "Product review pending — FSSAI license for cashew processing needs verification. Risk team flagged medium due to category-specific compliance requirements.",
    reviewedBy: "Deepa Iyer (Compliance)",
    products: ["W240 Cashew", "W320 Cashew", "Cashew Splits", "SW Cashew"],
  },
];

export const CHECKLIST_LABELS: Record<string, string> = {
  businessVerification: "Business Verification Completed",
  gstVerified: "GST Verified",
  panVerified: "PAN Verified",
  uboVerified: "UBO Verified",
  bankAccountVerified: "Bank Account Verified",
  agreementSigned: "Agreement Signed",
  productReviewApproved: "Product Review Approved",
  riskRatingAssigned: "Risk Rating Assigned",
  complianceApproval: "Compliance Approval Completed",
};

export const STATUS_COLORS: Record<string, string> = {
  Paid: "bg-blue-100 text-blue-700",
  Accepted: "bg-amber-100 text-amber-700",
  "Ready for Dispatch": "bg-violet-100 text-violet-700",
  Completed: "bg-emerald-100 text-emerald-700",
  Cancelled: "bg-red-100 text-red-700",
};

export const SETTLEMENT_COLORS: Record<string, string> = {
  Released: "bg-emerald-100 text-emerald-700",
  Pending: "bg-amber-100 text-amber-700",
  "On Hold": "bg-orange-100 text-orange-700",
  "N/A": "bg-gray-100 text-gray-500",
};

export const RISK_COLORS: Record<string, string> = {
  Low: "bg-emerald-100 text-emerald-700",
  Medium: "bg-amber-100 text-amber-700",
  High: "bg-red-100 text-red-700",
  Unassigned: "bg-gray-100 text-gray-500",
};

export const PENNY_COLORS: Record<string, string> = {
  Verified: "text-emerald-600",
  Pending: "text-amber-600",
  Failed: "text-red-600",
};
